# Generated by Django 3.0 on 2019-12-13 11:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email_id',
            field=models.TextField(validators=[user.models.min_length_check]),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='name',
            field=models.CharField(max_length=255, validators=[user.models.min_length_check]),
        ),
    ]
