# Generated by Django 3.0 on 2019-12-13 11:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191213_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email_id',
            field=models.CharField(max_length=255, validators=[user.models.min_length_check]),
        ),
    ]
