# Generated by Django 3.0 on 2019-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191213_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
